// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp52VgBk0n2S55eO06u86UnznGJFM_DK8',
    appId: '1:835443713191:ios:c3027a41b60ac2bd1be782',
    messagingSenderId: '835443713191',
    projectId: 'storyforgenerations',
    storageBucket: 'storyforgenerations.firebasestorage.app',
    androidClientId: '835443713191-hkj2k66otit37ui6783vll4mmvtnjliv.apps.googleusercontent.com',
    iosClientId: '835443713191-t00k5j7o5ujm0h3nviegasngfj6t6ce0.apps.googleusercontent.com',
    iosBundleId: 'com.story.forgenerations',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAofh2h3u707wFnDz5vwVd4kSkyXbUFnfE',
    appId: '1:835443713191:android:0174e46fec6ddf401be782',
    messagingSenderId: '835443713191',
    projectId: 'storyforgenerations',
    storageBucket: 'storyforgenerations.firebasestorage.app',
  );

}